{% set version = '1.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcppclock
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppClock_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppClock/RcppClock_{{ version }}.tar.gz
  sha256: ebf046603c95a635c9bc83d9fd4b5b973dc0f1628ba4e88215cdac989cd1a940

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ stdlib('c') }}                # [not win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp >=1.0.7               # [build_platform != target_platform]
    - r-ggplot2                    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.0.7
    - r-ggplot2
  run:
    - r-base
    - r-rcpp >=1.0.7
    - r-ggplot2

test:
  commands:
    - $R -e "library('RcppClock')"           # [not win]
    - "\"%R%\" -e \"library('RcppClock')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RcppClock
  license: GPL-2.0-or-later
  summary: Time the execution of overlapping or unique 'Rcpp' code chunks using convenient methods,
    seamlessly write timing results to an 'RcppClock' object in the R global environment,
    and summarize and/or plot the results in R.
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: RcppClock
# Type: Package
# Title: Seamless 'Rcpp' Benchmarking
# Version: 1.1
# Date: 2021-11-01
# Author: Zach DeBruine
# Maintainer: Zach DeBruine <zacharydebruine@gmail.com>
# Description: Time the execution of overlapping or unique 'Rcpp' code chunks using convenient methods, seamlessly write timing results to an 'RcppClock' object in the R global environment, and summarize and/or plot the results in R.
# License: GPL (>= 2)
# Imports: Rcpp (>= 1.0.7), ggplot2
# LinkingTo: Rcpp
# RoxygenNote: 7.1.2
# Suggests: testthat (>= 3.0.0)
# Config/testthat/edition: 3
# NeedsCompilation: yes
# Packaged: 2021-11-04 10:54:35 UTC; Owner
# Repository: CRAN
# Date/Publication: 2021-11-06 15:00:19 UTC
